### ISSUE TITLE
CMake Error at CMakeLists.txt:4 (add_executable):

### ISSUE THREAD

**Issue by albertyou2** [danlipert/pctrack#1]
hi @danlipert 
When I was trying to cmake this project ,an error occurred and full log here:

-- Configuring done
CMake Error at CMakeLists.txt:4 (add_executable):
  Cannot find source file:

    src/sggl/opengl_data.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: pcvis
CMake Error: Cannot determine link language for target "pcvis".
-- Generating done
-- Build files have been written to: /home/sojoyoo/people_danlipert/build

I think this repo is missing a file named "opengl_data.c" ,is't it?
Where could find this file ?
Thanks!

**Comment by depp** [comment]
It looks like the OpenGL loader generator somehow didn't make it over.  This should be trivial to replace.

**Comment by albertyou2** [comment]
HI@depp
Do you mean that i should reinstall opengl on my machine?
